version: "3.9"

services:
  # Syslog Server
  syslog:
    image: balabit/syslog-ng:4.6.0
    container_name: tech-store-syslog
    restart: unless-stopped
    command: ["--no-caps"]
    volumes:
      - ./docker/syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - syslog_data:/var/log/syslog-ng
    ports:
      - "514:514/udp"
      - "601:601/tcp"
    networks:
      - tech_store_network

volumes:
  syslog_data:

networks:
  tech_store_network:
    driver: bridge
