version: "3.9"

services:
  tech-store:
    image: postgres:17
    container_name: tech-store-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - tech_store_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tech_store_network

volumes:
  tech_store_pg_data:

networks:
  tech_store_network:
    driver: bridge
