sonar.projectKey=techstore-backend-key_techstore
sonar.organization=ORGANIZATION
sonar.projectName=Techstore API

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/*Application.java,**/dto/**

sonar.sourceEncoding=UTF-8