# ZAP API Scan Configuration
# RULE_ID LEVEL DESCRIPTION
# FAIL (block), WARN (default), IGNORE (skip)

10015	IGNORE
10020	IGNORE
10021	IGNORE
10202	IGNORE
20012	IGNORE
20016	IGNORE
3	IGNORE
40012	FAIL
40014	FAIL
40018	FAIL
90019	FAIL
90020	FAIL
90023	FAIL
