@version: 4.2

# Receber logs via UDP e TCP
source s_network {
    udp(ip(0.0.0.0) port(514));
    tcp(ip(0.0.0.0) port(601));
};

# Separar logs de auditoria dos restantes
filter f_audit {
    message("event=LOGIN_ATTEMPT") or
    message("event=REGISTER_ATTEMPT") or
    message("event=LOGOUT_ATTEMPT") or
    message("event=TOKEN_REFRESH") or
    message("event=INVITE_ATTEMPT") or
    message("event=CONFIRM_INVITE") or
    message("event=PASSWORD_RESET_REQUEST") or
    message("event=PASSWORD_UPDATE") or
    message("event=MFA_ENROLL_SUCCESS") or
    message("event=MFA_ENROLL_FAILURE") or
    message("event=MFA_VERIFY_SUCCESS") or
    message("event=MFA_VERIFY_FAILURE") or
    message("event=MFA_CHALLENGE_SUCCESS") or
    message("event=MFA_CHALLENGE_FAILURE") or
    message("event=MFA_CHALLENGE_VERIFY_SUCCESS") or
    message("event=MFA_CHALLENGE_VERIFY_FAILURE") or
    message("event=MFA_UNENROLL_SUCCESS") or
    message("event=MFA_UNENROLL_FAILURE") or
    message("event=CART_CREATION") or
    message("event=CART_UPDATE") or
    message("event=CART_ITEM_ADDED") or
    message("event=CART_ITEM_MERGED") or
    message("event=CART_CREATION_FAILURE") or
    message("event=CART_UPDATE_FAILURE") or
    message("event=CART_RETRIEVED") or
    message("event=ORDER_CREATION_ATTEMPT") or
    message("event=ORDER_CREATION_SUCCESS") or
    message("event=ORDER_CREATION_FAILURE") or
    message("event=CUSTOMER_ORDER_LIST_ATTEMPT") or
    message("event=CUSTOMER_ORDER_LIST_SUCCESS") or
    message("event=CUSTOMER_ORDER_LIST_FAILURE") or
    message("event=CARRIER_ORDER_LIST_ATTEMPT") or
    message("event=CARRIER_ORDER_LIST_SUCCESS") or
    message("event=CARRIER_ORDER_LIST_FAILURE") or
    message("event=ORDER_PICKUP_ATTEMPT") or
    message("event=ORDER_PICKUP_SUCCESS") or
    message("event=ORDER_PICKUP_FAILURE") or
    message("event=PENDING_ORDER_LIST_ATTEMPT") or
    message("event=PENDING_ORDER_LIST_SUCCESS") or
    message("event=PENDING_ORDER_LIST_FAILURE") or
    message("event=MANAGER_ORDERS_LIST_ATTEMPT") or
    message("event=MANAGER_ORDERS_FILTERED") or
    message("event=MANAGER_ORDERS_ACCESS_FAILURE") or
    message("event=PRODUCT_CREATION") or
    message("event=PRODUCT_CREATION_FAILURE") or
    message("event=STOCK_UPDATE") or
    message("event=STOCK_UPDATE_FAILURE") or
    message("event=PRODUCT_UPDATE") or
    message("event=PRODUCT_UPDATE_FAILURE")
};

# Destino - ficheiro de auditoria
destination d_audit {
    file("/var/log/syslog-ng/audit.log"
        template("${ISODATE} ${HOST} ${MSG}\n")
        perm(0644)
    );
};

# Destino - ficheiro geral
destination d_general {
    file("/var/log/syslog-ng/application.log"
        template("${ISODATE} ${HOST} ${MSG}\n")
        perm(0644)
    );
};

# Regras
log { source(s_network); filter(f_audit); destination(d_audit); };
log { source(s_network); destination(d_general); };