@version: 4.2

# Receber logs via UDP e TCP
source s_network {
    udp(ip(0.0.0.0) port(514));
    tcp(ip(0.0.0.0) port(601));
};

# Separar logs de auditoria dos restantes
filter f_audit {
    message("event=LOGIN_ATTEMPT") or
    message("event=TOKEN_REFRESH")
};

# Destino - ficheiro de auditoria
destination d_audit {
    file("/var/log/syslog-ng/audit.log"
        template("${ISODATE} ${HOST} ${MSG}\n")
    );
};

# Destino - ficheiro geral
destination d_general {
    file("/var/log/syslog-ng/application.log"
        template("${ISODATE} ${HOST} ${MSG}\n")
    );
};

# Regras
log { source(s_network); filter(f_audit); destination(d_audit); };
log { source(s_network); destination(d_general); };