@startuml

left to right direction

together{
actor User
}

together{
    (Search by product name) as A1 #LightBlue
    (Input product name) as A2 #LightBlue
    (Parameterized queries) as A3 #LightBlue
    (Input length validation) as A4 #LightBlue
    (Enforce rate limiting) as A5 #LightBlue
    (Log Searches) as A6 #LightBlue
}
together{
(SQL injection attack) as AT1
(Catalog scraping) as AT2

}

together{
actor Malicious_User #red
}


User -- A1

Malicious_User -right[#red]- AT1
Malicious_User -right[#red]- AT2


AT1 -[#red,dashed]left-> A1 : threatens
AT2 -[#red,dashed]left-> A1 : threatens

A3 -[#green,dashed]-> AT1 : mitigates
A4 -[#green,dashed]-> AT1 : mitigates
A5 -[#green,dashed]-> AT2 : mitigates
A6 -[#green,dashed]-> AT2 : mitigates

A1 .> A2 : <<Includes>>
A1 .> A3 : <<Includes>>
A1 .> A4 : <<Includes>>
A1 .> A5 : <<Includes>>
A1 .> A6 : <<Includes>>







@enduml
