@startuml

left to right direction

together{
actor User
}

together{
    (Browse Products) as A1 #LightBlue
    (Enforce Rate Limiting) as A2 #LightBlue
    (Filter response Fields) as A3 #LightBlue
    (Log Access) as A4 #LightBlue
}
together{
(Flood endpoint) as AT1
(Harvest product data) as AT2
(Access Internal Fields) as AT3
}

together{
actor Malicious_User #red
}


User -- A1

Malicious_User -right[#red]- AT1
Malicious_User -right[#red]- AT2
Malicious_User -right[#red]- AT3

AT1 -[#red,dashed]left-> A1 : threatens
AT2 -[#red,dashed]left-> A1 : threatens
AT3 -[#red,dashed]left-> A1 : threatens

A2 -[#green,dashed]-> AT1 : mitigates
A2 -[#green,dashed]-> AT2 : mitigates
A3 -[#green,dashed]-> AT3 : mitigates
A4 -[#green,dashed]-> AT2 : mitigates

A1 .> A2 : <<Includes>>
A1 .> A3 : <<Includes>>
A1 .> A4 : <<Includes>>







@enduml
