spring:
  application:
    name: TechStore

  profiles:
    active: bootstrap

  config:
    import:
      - optional:classpath:ratelimit.yaml
      - optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}

    from:
      email: ${MAIL_FROM}
      name: ${MAIL_FROM_NAME}

    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
server:
  forward-headers-strategy: framework
  servlet:
    context-path: /api
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: info, health

supabase:
  url: ${SUPABASE_URL}
  anon-key: ${SUPABASE_ANON_KEY}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}
  webhook-secret: ${SUPABASE_WEBHOOK_SECRET}
  redirect-url: ${SUPABASE_REDIRECT_URL}
  jwt-secret: ${SUPABASE_JWT_SECRET}
  issuer: ${SUPABASE_ISSUER}
  jwks-url: ${SUPABASE_JWKS_URL}
  jwt-audience: ${SUPABASE_JWT_AUDIENCE}
