name: Snyk Scan
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  snyk-sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Snyk
        run: npm install -g snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk Code test (SAST)
        run: snyk code test --org=${{ secrets.SNYK_ORG_ID }}
        working-directory: backend

  snyk-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and export dependency tree
        run: |
          mvn clean install -DskipTests
          mvn dependency:tree > dep-tree.txt
        working-directory: backend
        env:
          MAVEN_OPTS: "-Xmx2g"

      - uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --org=${{ secrets.SNYK_ORG_ID }} --file=pom.xml
          directory: backend