name: Snyk Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: mvn clean install -DskipTests
        working-directory: backend

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code test (SAST)
        run: snyk code test --org=2324a6a0-65da-44fb-922e-340f88ffea53
        working-directory: backend

      - name: Run Snyk Open Source test (SCA)
        run: snyk test --org=2324a6a0-65da-44fb-922e-340f88ffea53 --all-projects
        working-directory: backend
        continue-on-error: true  # remove this if you want it to block PRs on vulnerabilities
