name: Deploy on main (docker only)

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            sudo docker system prune -af

            # ---- Docker login on SERVER ----
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # ---- Network ----
            sudo docker network inspect techstore-net >/dev/null 2>&1 || sudo docker network create techstore-net

            BACKEND_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/techstore:latest"
            # FRONTEND_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/techstore:frontend-latest"

            sudo docker pull "$BACKEND_IMAGE"
            # sudo docker pull "$FRONTEND_IMAGE"


      - name: Start containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            BACKEND_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/techstore:latest"
            # FRONTEND_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/techstore:frontend-latest"

            # ---- Backend ----
            sudo docker rm -f techstore || true
            sudo docker run -d \
              --name techstore \
              --restart unless-stopped \
              --network techstore-net \
              -p 8080:8081 \
              --env-file /opt/techstore/backend.env \
              "$BACKEND_IMAGE"

            # ---- Frontend ----
            # sudo docker rm -f techstore-frontend || true
            # sudo docker run -d \
            #   --name techstore-frontend \
            #   --restart unless-stopped \
            #   --network techstore-net \
            #   -p 3002:3000 \
            #   "$FRONTEND_IMAGE"

            sudo docker image prune -f
