name: dev

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  security-secrets:
    uses: ./.github/workflows/security-secrets.yml
    permissions:
      security-events: write
      contents: read
    secrets:
      GITLEAKS_SHA256: ${{ secrets.GITLEAKS_SHA256 }}

  dependency-scanning:
    uses: ./.github/workflows/dependecies-analysis.yaml
    needs:
      - build-test
    permissions:
      security-events: write
      actions: read
      contents: read
    secrets: inherit
