name: dev

on:
  push:
    branches:
      - dev

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  sast:
    needs: build-test
    uses: ./.github/workflows/reusable/security-sast.yml
    secrets: inherit