name: feature

on:
  push:
    branches-ignore:
      - dev
      - main
      - docs/*

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  security-secrets:
    uses: ./.github/workflows/security-secrets.yml
    permissions:
      security-events: write
      contents: read
    secrets:
      GITLEAKS_SHA256: ${{ secrets.GITLEAKS_SHA256 }}

  dast-scan:
    uses: ./.github/workflows/dast-scan.yml
    needs:
      - build-test
    permissions:
      security-events: write
      contents: read
      checks: write
      pull-requests: write
    secrets: inherit

  sast:
    needs: build-test
    uses: ./.github/workflows/security-sast.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
