name: feature

on:
  push:
    branches-ignore:
      - dev
      - main
      - docs/*

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  security-secrets:
    uses: ./.github/workflows/security-secrets.yml
    permissions:
      security-events: write
      contents: read
