name: main

on:
  push:
    branches:
      - main

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  security-secrets:
    uses: ./.github/workflows/security-secrets.yaml

  release-please:
    uses: ./.github/workflows/release.yml 
