name: main

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  security-secrets:
    uses: ./.github/workflows/security-secrets.yml
    permissions:
      security-events: write
      contents: read
    secrets:
      GITLEAKS_SHA256: ${{ secrets.GITLEAKS_SHA256 }}

  release-please:
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    needs:
      - build-test
      - security-secrets
