name: main

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  security-secrets:
    uses: ./.github/workflows/security-secrets.yml
    permissions:
      security-events: write
      contents: read
    secrets:
      GITLEAKS_SHA256: ${{ secrets.GITLEAKS_SHA256 }}

  dependency-scanning:
    uses: ./.github/workflows/dependecies-analysis.yaml
    needs:
      - build-test
    permissions:
      security-events: write
      actions: read
      contents: read
    secrets: inherit

  dast-scan:
    uses: ./.github/workflows/dast-scan.yml
    permissions:
      security-events: write
      contents: read
      checks: write
      pull-requests: write
    secrets: inherit

  docker:
    if: github.event_name == 'push'
    uses: ./.github/workflows/docker.yml
    needs:
      - security-secrets
      - dependency-scanning
      - dast-scan
    permissions:
      contents: read
      packages: write
    secrets: inherit

  deploy:
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    needs:
      - docker
    secrets: inherit

  release-please:
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    needs:
      - deploy
