name: security-sast.yml
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonar:
    name: SonarQube SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build project (skip tests)
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: backend/target/site/jacoco

      - name: SonarCloud Scan (main/dev with Quality Gate)
        if: |
                  github.ref == 'refs/heads/main' ||
                  github.ref == 'refs/heads/dev' ||
                  github.base_ref == 'main' ||
                  github.base_ref == 'dev'
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: backend
          args: >
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: SonarCloud Scan (feature branches)
        if: |
          github.ref != 'refs/heads/main' && 
          github.ref != 'refs/heads/dev' &&
          github.base_ref != 'main' &&
          github.base_ref != 'dev'
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io