name: Security Secrets Scan

on:
  workflow_call:
    
jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -O gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        run: |
          gitleaks detect \
            --source backend \
            --report-format json \
            --report-path gitleaks-report.json \
            --exit-code 1 \
            --redact